backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

locale: "ja"

publish_mode: editorial_workflow

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "タイトル", name: "title", widget: "string" }
      - { label: "投稿日", name: "date", widget: "datetime" }
      - { label: "画像", name: "image", widget: "image", required: false }
      - { label: "説明", name: "description", widget: "string" }
      - { label: "本文", name: "body", widget: "markdown" }
